<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <RootNamespace>Keyfactor.Extensions.Aws</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>0.5.2</Version>
    <RepositoryUrl>https://github.com/Keyfactor/aws-auth-library</RepositoryUrl>
    <AssemblyName>Keyfactor.Extensions.Aws.Auth</AssemblyName>
    <Copyright>Copyright (c) Keyfactor 2025</Copyright>
    <Company>Keyfactor</Company>
    <Authors>Keyfactor</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Keyfactor/aws-auth-library</RepositoryUrl>
    <Description>This library provides multiple methods for resolving AWS Credentials using a set of defined fields that are defined in an extension.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.6.1" />
    <PackageReference Include="AWSSDK.IdentityManagement" Version="4.0.9.22" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="4.0.6.3" />
    <PackageReference Include="Keyfactor.Logging" Version="1.1.2" />
    <PackageReference Include="Keyfactor.Orchestrators.IOrchestratorJobExtensions" Version="1.0.0" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
